### ISSUE TITLE
Provide an easy way to get Response in IRetryPolicy

### ISSUE THREAD

**Issue by epeshk** [vostok/clusterclient.core#1]
Now `IRetryPolicy.NeedToRetry` method accept `IList<ReplicaResult> results` an there is no easy way to get final `Response` which will be returned to caller.

Current signature: `IRetryPolicy.NeedToRetry(Request request, RequestParameters parameters, IList<ReplicaResult> results)`

I suggest change signature of this method to `IRetryPolicy.NeedToRetry(ClusterResult result)`

`ClusterResult` provides access to source `Request`, list of replica results and selected `Response`. Also we need to extend `ClusterResult` with `RequestParameters`, because `IRetryPolicy.NeedToRetry` accept source request parameters too.

**Comment by kungasc** [comment]
obsolete
