### ISSUE TITLE
Unable to write custom request retry module without replicas result reset

### ISSUE THREAD

**Issue by goodoldlameme** [vostok/clusterclient.core#18]
I found out that you need to write this line at the end of while(true) loop in custom request retry module to make it work correcty: ```(context as RequestContext)?.ResetReplicaResults();```

But RequestContext is internal so it makes it uneasy to write custom request retry module. May you please make it public, because it seems you cant write custom request retry module without that.

**Comment by iloktionov** [comment]
`ResetReplicaResults` method is public now, closing this issue.
