### ISSUE TITLE
UriBuilder: Relative URIs are treated as filesytem paths on Unix systems

### ISSUE THREAD

**Issue by minya** [vostok/clusterclient.core#26]
new UriBuilder("/v1/orders").Build() results in different URIs in Windows and Unix. For some reasons on Unix it will be "file:///v1/orders". So I catch errors like
```
ERROR Request 'GET file:///v1/orders/1d1373f6-d142-4ce7-b733-47ef48583324/paymentInfo' to 'SelfService.Api via Singular' has failed with status 'IncorrectArguments'. Response code = 0 ('Unknown'). Time = 1.333 milliseconds.
```
Expected behaviour: it works consistently across different platforms.

**Comment by kungasc** [comment]
duplicates https://github.com/vostok/clusterclient.core/issues/6
