### ISSUE TITLE
Incorrect behavior with relative URLs on *nix systems

### ISSUE THREAD

**Issue by terotgut** [vostok/clusterclient.core#6]
According to https://github.com/dotnet/corefx/issues/22098 there is different behaviour of request with relative URLs. 

Example:

```
var authenticationRequest = Request.Post("/v3/connect");

var client = new ClusterClient(log,
                s =>
                {
                    s.Transport = new UniversalTransport(log);
                    s.ClusterProvider = new FixedClusterProvider("https://myservice.com");
                });
```

On mac os it will generate request: `POST file:///v3/connect` and on Windows : `POST https://myservice.com/v3/connect`

Can be reproduced with: 
Vostok.ClusterClient.Core 0.1.8
Vostok.ClusterClient.Transport 0.1.5

**Comment by kungasc** [comment]
Fixed at 0.1.27
